#!/usr/bin/env bash
# Script configures web-02 to be identical to web-01 and adds a custom Nginx response header.
sudo apt-get update
sudo apt-get -y install nginx

# configure firewall to allow request through port 80
sudo ufw allow 'Nginx HTTP'

sudo mkdir -p /var/www/html/

# change permissions to allow user to create, delete, and modify files in the directory
sudo chmod -R 755 /var/www

# create the index page
echo "Hello World!" | sudo tee /var/www/html/index.html

# create the 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# configure redirect for a single page(/redirect_me) and add header to display hostname
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.ochiengronnie.netlify.app permanent;\n\tadd_header X-Served-By \$HOSTNAME;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# configure redirect for 404 error page
string_for_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# restart the web server
sudo service nginx restart
