#!/usr/bin/env bash
# Generates a MySQL dump and creates a compressed archive out of it.

# Generate a MySQL dump
mysqldump -u root -p tyrell_corp > backup.sql

# Create a compressed archive out of it and let the archive be day-month-year.tar.gz
tar -czvf "$(date +%d-%m-%Y).tar.gz backup.sql"
