#!/usr/bin/env bash
# Script automates fix for web server to listen on port 80

# install nginx
sudo apt-get update
sudo apt-get -y install nginx

# configure firewall to allow request through port 80
sudo ufw allow 'Nginx HTTP'

# configure nginx to listen on port 80
sudo sed -i "s/listen 80 default_server;/listen 80;/" /etc/nginx/sites-enabled/default

# restart the web server
sudo service nginx restart