#!/usr/bin/env bash
# Script displays Best School 10 times, but for the 9th iteration, displays "Hi" instead of "Best School"

i=1
while [ $i -le 10 ]
do
    if [ $i -eq 9 ]
    then
        echo "Hi"
    else
        echo "Best School"
    fi
    i=$(( i + 1 ))
done
