#!/usr/bin/env bash
# Script that accepts one argument. The script should run the whoami command under the user passed as an argument

if [ "$#" -lt 1 ]; then
    echo "Usage: 0-iamsomeoneelse USERNAME"
else
    sudo -u "$1" whoami
fi